# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:10.4
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080

